# Generated by Django 5.2.1 on 2025-06-18 03:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a descriptive title for your post.",
                        max_length=255,
                        verbose_name="Post Title",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Provide details about the post.",
                        verbose_name="Post Description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("service", "Service"), ("rent", "Rent")],
                        help_text="Select the category for the post.",
                        max_length=15,
                        verbose_name="Category",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="0000000000",
                        help_text="Enter your contact phone number.",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Views"
                    ),
                ),
                (
                    "votes",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Votes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Enter the location relevant to the post.",
                        max_length=255,
                        verbose_name="Location",
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        blank=True,
                        help_text="Enter the price range if applicable.",
                        max_length=100,
                        verbose_name="Price Range",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Anonymous",
                        help_text="Enter your name or username.",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="posts.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
