# Generated by Django 5.1.4 on 2025-02-01 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(
                default="Anonymous",
                help_text="Enter your name or username.",
                max_length=100,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="phone_number",
            field=models.CharField(
                default="0000000000",
                help_text="Enter your contact phone number.",
                max_length=15,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("job", "Job"), ("service", "Service")],
                help_text="Select the category for the post.",
                max_length=10,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created At"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(
                help_text="Provide details about the post.",
                verbose_name="Post Description",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Enter a descriptive title for your post.",
                max_length=255,
                verbose_name="Post Title",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Views"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="votes",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Votes",
            ),
        ),
    ]
