# Generated by Django 5.2.4 on 2025-08-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = []
