# Generated by Django 5.1.4 on 2025-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Enter the location relevant to the post.",
                max_length=255,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="price_range",
            field=models.CharField(
                blank=True,
                help_text="Enter the price range if applicable.",
                max_length=100,
                verbose_name="Price Range",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("job", "Job"),
                    ("service", "Service"),
                    ("rent", "Rent"),
                    ("looking_for", "Looking For"),
                    ("found", "Found"),
                    ("asking_for", "Asking For"),
                ],
                help_text="Select the category for the post.",
                max_length=15,
                verbose_name="Category",
            ),
        ),
    ]
