# Generated by Django 5.1.4 on 2025-02-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_location_post_price_range_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("job", "Job"),
                    ("service", "Service"),
                    ("rent", "Rent"),
                    ("looking_for", "Looking For"),
                ],
                help_text="Select the category for the post.",
                max_length=15,
                verbose_name="Category",
            ),
        ),
    ]
