# Generated by Django 5.2.4 on 2025-08-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_remove_comment_name_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
