# Generated by Django 5.2.4 on 2025-08-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_userprofile_receive_marketing_emails_and_more"),
        ("posts", "0005_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="Select if this post is associated with a business",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="postss",
                to="directory.business",
                verbose_name="Associated Business",
            ),
        ),
    ]
