# Generated by Django 5.2.4 on 2025-09-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_comment_options_post_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("service", "Service"),
                    ("rent", "Rent"),
                    ("job", "Job"),
                    ("event", "Event"),
                ],
                help_text="Select the category for the post.",
                max_length=15,
                verbose_name="Category",
            ),
        ),
    ]
