# Generated by Django 5.2.1 on 2025-05-20 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="Page URL")),
                ("method", models.CharField(default="GET", max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("referrer", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Visit Time"
                    ),
                ),
                (
                    "is_authenticated",
                    models.BooleanField(default=False, verbose_name="Logged In"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sessions.session",
                        verbose_name="Session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Authenticated User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Visit",
                "verbose_name_plural": "Page Visits",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="analytics_p_timesta_8f24f0_idx"
                    ),
                    models.Index(fields=["path"], name="analytics_p_path_3fa0ca_idx"),
                    models.Index(
                        fields=["user"], name="analytics_p_user_id_91fb05_idx"
                    ),
                    models.Index(
                        fields=["session"], name="analytics_p_session_9a744f_idx"
                    ),
                    models.Index(
                        fields=["is_authenticated"],
                        name="analytics_p_is_auth_d94743_idx",
                    ),
                ],
            },
        ),
    ]
