# Generated by Django 5.2.4 on 2025-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDashboardLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "📊 Analytics Dashboard",
                "verbose_name_plural": "📊 Analytics Dashboard",
                "managed": False,
            },
        ),
    ]
