# Generated by Django 5.1.4 on 2025-02-04 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Management", "Management"),
                            ("Maintenance", "Maintenance"),
                            ("Veterinary", "Veterinary"),
                            ("Operations", "Operations"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Needs Repair", "Needs Repair"),
                            ("Broken", "Broken"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hours_worked", models.FloatField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="inventory.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_issued", models.DateTimeField(auto_now_add=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Needs Repair", "Needs Repair"),
                            ("Broken", "Broken"),
                        ],
                        default="Good",
                        max_length=50,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.employee",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Equipment",
                "verbose_name_plural": "Employee Equipment",
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.equipmentcategory",
            ),
        ),
        migrations.CreateModel(
            name="EquipmentDamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("reported_date", models.DateTimeField(auto_now_add=True)),
                (
                    "employee_equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_reports",
                        to="inventory.employeeequipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farm_equipment",
                to="inventory.farm",
            ),
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("planted_date", models.DateField()),
                ("harvest_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Growing", "Growing"), ("Harvested", "Harvested")],
                        max_length=100,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="inventory.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("Healthy", "Healthy"),
                            ("Sick", "Sick"),
                            ("Injured", "Injured"),
                            ("Quarantined", "Quarantined"),
                        ],
                        default="Healthy",
                        max_length=50,
                    ),
                ),
                ("last_vaccinated", models.DateField(blank=True, null=True)),
                ("weight", models.FloatField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_animals",
                        to="inventory.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="inventory.equipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.FloatField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[("kg", "Kilograms"), ("L", "Liters")], max_length=10
                    ),
                ),
                ("in_stock", models.FloatField(default=0)),
                ("out_stock", models.FloatField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.stockcategory",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_items",
                        to="inventory.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Item",
                "verbose_name_plural": "Stock Items",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out")], max_length=10
                    ),
                ),
                ("quantity", models.FloatField()),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.stockitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("date_administered", models.DateField()),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="inventory.animal",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.UniqueConstraint(
                fields=("farm", "tag_number"), name="unique_farm_animal_tag"
            ),
        ),
    ]
