# Generated by Django 5.2.1 on 2025-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_alter_conversation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
