# Generated by Django 5.1.4 on 2025-01-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
