# Generated by Django 5.1.4 on 2025-01-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_request_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shop",
            ),
        ),
    ]
