# Generated by Django 5.2.1 on 2025-07-18 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0002_alter_product_image_productview_rewardclaim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productview",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productview",
            name="referrer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productview",
            name="source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productview",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productview",
            name="view_duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["product", "viewed_at"], name="pos_system__product_d22c32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["session_key"], name="pos_system__session_a999f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["viewed_at"], name="pos_system__viewed__7dbeee_idx"
            ),
        ),
    ]
