# Generated by Django 5.2.1 on 2025-07-18 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0004_mark_claimed_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productview",
            name="claim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pos_system.rewardclaim",
            ),
        ),
        migrations.AddField(
            model_name="productview",
            name="claimed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="productview",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["claimed"], name="pos_system__claimed_ba73e5_idx"
            ),
        ),
    ]
