# Generated by Django 5.2.1 on 2025-07-25 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0005_productview_claim_productview_claimed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["product", "viewer"], name="pos_system__product_bf141e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productview",
            index=models.Index(
                fields=["product", "session_key"], name="pos_system__product_ddec88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("viewer__isnull", False)),
                fields=("product", "viewer"),
                name="unique_product_viewer",
            ),
        ),
        migrations.AddConstraint(
            model_name="productview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("product", "session_key"),
                name="unique_product_session",
            ),
        ),
    ]
