# Generated by Django 5.2.4 on 2025-08-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_userprofile_receive_marketing_emails_and_more"),
        ("pos_system", "0006_productview_pos_system__product_bf141e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_fragile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(
                choices=[
                    ("light", "Light (<1kg)"),
                    ("medium", "Medium (1-5kg)"),
                    ("heavy", "Heavy (>5kg)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.CreateModel(
            name="DeliveryFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "per_km_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_distance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum distance in km for this fee to apply",
                        max_digits=6,
                    ),
                ),
                (
                    "max_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum distance in km for this fee to apply (leave blank for no limit)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "size_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for large items",
                        max_digits=5,
                    ),
                ),
                (
                    "weight_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for heavy items",
                        max_digits=5,
                    ),
                ),
                (
                    "fragile_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for fragile items",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_fees",
                        to="directory.business",
                    ),
                ),
            ],
            options={
                "ordering": ["min_distance"],
            },
        ),
    ]
