# Generated by Django 5.2.4 on 2025-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0007_product_is_fragile_product_size_product_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_fragile",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="delivery_latitude",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="delivery_longitude",
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=30.0,
                help_text="Fixed delivery fee for this product (K30)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Percentage of product total to add to delivery fee",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="has_delivery",
            field=models.BooleanField(
                default=True, help_text="Whether this product requires delivery"
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="requires_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sale",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total delivery fee for this sale",
                max_digits=10,
            ),
        ),
        migrations.DeleteModel(
            name="DeliveryFee",
        ),
    ]
