# Generated by Django 5.2.4 on 2025-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0008_remove_product_is_fragile_remove_product_size_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="requires_delivery",
            new_name="needs_delivery",
        ),
        migrations.RemoveField(
            model_name="product",
            name="delivery_fee",
        ),
        migrations.RemoveField(
            model_name="product",
            name="delivery_percentage",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_delivery",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="delivery_address",
        ),
        migrations.AlterField(
            model_name="sale",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
