# Generated by Django 5.2.4 on 2025-08-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pos_system",
            "0010_remove_sale_delivery_fee_remove_sale_needs_delivery_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
