# Generated by Django 5.2.4 on 2025-08-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0012_alter_orderitem_options_remove_order_is_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_read_business",
            field=models.BooleanField(default=False),
        ),
    ]
