# Generated by Django 5.2.4 on 2025-09-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_system", "0014_chatlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "Piece"),
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("litre", "Litre"),
                    ("ml", "Millilitre"),
                    ("dozen", "Dozen"),
                    ("packet", "Packet"),
                    ("box", "Box"),
                ],
                default="piece",
                max_length=20,
            ),
        ),
    ]
