# Generated by Django 5.2 on 2026-07-28 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_alter_business_options'),
        ('pos_system', '0015_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zra_item_class_code',
            field=models.CharField(blank=True, help_text='ZRA/UNSPSC item classification code (level 4).', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_item_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_item_type',
            field=models.CharField(choices=[('1', 'Raw material'), ('2', 'Finished product'), ('3', 'Service')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_last_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_origin_country_code',
            field=models.CharField(default='ZM', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_package_unit_code',
            field=models.CharField(default='OU', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_quantity_unit_code',
            field=models.CharField(default='EA', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='zra_tax_category',
            field=models.CharField(choices=[('A', 'A - VAT 16%'), ('B', 'B - VAT 16%'), ('C1', 'C1 - Export 0%'), ('C2', 'C2 - Export 0%'), ('C3', 'C3 - Export 0%'), ('D', 'D - Exempt 0%'), ('E', 'E - Disbursement 0%'), ('RVAT', 'RVAT - Reverse VAT 16%'), ('F', 'F - Service charge 10%'), ('IPL1', 'IPL1 - Insurance premium levy 5%'), ('IPL2', 'IPL2 - Reinsurance premium levy 0%'), ('TL', 'TL - Tourism levy 1.5%'), ('ECM', 'ECM - Excise coal 5%'), ('EXEEG', 'EXEEG - Excise electricity 3%'), ('TOT', 'TOT - Turnover tax 0%')], default='TOT', max_length=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='cis_invoice_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency_code',
            field=models.CharField(default='ZMW', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_tpin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscal_status',
            field=models.CharField(choices=[('NON_FISCAL', 'Standard Swiftfind receipt'), ('PENDING', 'Pending ZRA'), ('CERTIFIED', 'Certified by ZRA/VSDC'), ('FAILED', 'ZRA/VSDC failed')], default='NON_FISCAL', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='fiscalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('COPY', 'Copy'), ('TRAINING', 'Training'), ('PROFORMA', 'Proforma')], default='NORMAL', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_sales', to='pos_system.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='stock_sync_status',
            field=models.CharField(default='NOT_REQUIRED', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_NOTE', 'Debit note')], default='SALE', max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_internal_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_machine_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_publication_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_qr_code_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_receipt_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_request',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sale',
            name='zra_sdc_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_class_code_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_code_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='package_unit_code_snapshot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity_unit_code_snapshot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_category_snapshot',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='FiscalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_events', to='pos_system.sale')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ZRAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10)),
                ('tpin', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'TPIN must contain exactly 10 digits.')])),
                ('branch_id', models.CharField(default='000', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Branch ID must contain exactly 3 digits.')])),
                ('cis_number', models.CharField(blank=True, max_length=100)),
                ('software_version', models.CharField(default='1.0.0', max_length=30)),
                ('vsdc_base_url', models.URLField(blank=True, help_text="Base URL of the business's local or hosted ZRA VSDC service.")),
                ('device_initialized', models.BooleanField(default=False)),
                ('sdc_id', models.CharField(blank=True, max_length=100)),
                ('last_code_sync_at', models.DateTimeField(blank=True, null=True)),
                ('default_currency_code', models.CharField(default='ZMW', max_length=3)),
                ('default_exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('request_timeout_seconds', models.PositiveSmallIntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zra_configuration', to='directory.business')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('NORMAL', 'Normal'), ('COPY', 'Copy'), ('TRAINING', 'Training'), ('PROFORMA', 'Proforma')], max_length=12)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('CREDIT_NOTE', 'Credit note'), ('DEBIT_NOTE', 'Debit note')], max_length=12)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'invoice_type', 'transaction_type'), name='unique_business_fiscal_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('cis_invoice_number__isnull', False)), fields=('business', 'invoice_type', 'transaction_type', 'cis_invoice_number'), name='unique_business_cis_invoice_number'),
        ),
    ]
