# Generated by Django 5.2.1 on 2025-06-18 03:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("in", "In Venue"), ("out", "Not in Venue")],
                        default="out",
                        max_length=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Unknown Company", max_length=255),
                ),
                ("company_address", models.TextField(default="Unknown Address")),
                (
                    "company_email",
                    models.EmailField(default="unknown@example.com", max_length=254),
                ),
                (
                    "phone_number",
                    models.CharField(default="000-000-0000", max_length=50),
                ),
                (
                    "customer_name",
                    models.CharField(default="Unknown Customer", max_length=255),
                ),
                ("date", models.DateField()),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("QUOTATION", "Quotation"),
                            ("RECEIPT", "Receipt"),
                            ("DELIVERY_NOTE", "Delivery Note"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "paper_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "prepared_by",
                    models.CharField(default="Unknown Preparer", max_length=255),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "vat_rate",
                    models.IntegerField(
                        choices=[
                            (0, "No VAT (0%)"),
                            (5, "VAT 5%"),
                            (10, "VAT 10%"),
                            (16, "VAT 16%"),
                            (20, "VAT 20%"),
                        ],
                        default=0,
                        help_text="Select the applicable VAT rate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="paper.paper",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
