# Generated by Django 5.1.4 on 2025-01-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
