# Generated by Django 5.1.4 on 2025-02-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="paper_type",
            field=models.CharField(
                choices=[
                    ("QUOTATION", "Quotation"),
                    ("RECEIPT", "Receipt"),
                    ("DELIVERY_NOTE", "Delivery Note"),
                ],
                max_length=20,
            ),
        ),
    ]
