# Generated by Django 5.1.4 on 2025-03-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0002_alter_paper_paper_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
    ]
