# Generated by Django 5.1.4 on 2025-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0003_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
    ]
