# Generated by Django 5.1.4 on 2025-03-21 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0004_guest_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
