# Generated by Django 5.1.4 on 2025-03-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0006_alter_guest_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="status",
            field=models.CharField(
                choices=[("in", "In Venue"), ("out", "Not in Venue")],
                default="out",
                max_length=3,
            ),
        ),
    ]
