# Generated by Django 5.1.4 on 2025-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paper", "0007_guest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="vat_rate",
            field=models.IntegerField(
                choices=[
                    (0, "No VAT (0%)"),
                    (5, "VAT 5%"),
                    (10, "VAT 10%"),
                    (16, "VAT 16%"),
                    (20, "VAT 20%"),
                ],
                default=0,
                help_text="Select the applicable VAT rate",
            ),
        ),
    ]
