# Generated by Django 5.2 on 2026-06-26 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_clarificationmessage_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PO', 'Purchase Order'), ('DN', 'Delivery Note'), ('GRN', 'Goods Received Note'), ('INV', 'Invoice')], max_length=10, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveIntegerField(default=4)),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('sent_successfully', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.CharField(choices=[('HEAD_TEACHER', 'Head teacher'), ('COMMITTEE', 'Procurement committee'), ('DEBS_PEO', 'DEBS/PEO')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for correction')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='procurement.procurementrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('request', 'approver_role')},
            },
        ),
    ]
