# Generated by Django 5.2 on 2026-06-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_documentnumbersetting_emailnotification_approvalstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='items_delivered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='delivery_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='quotation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentnumbersetting',
            name='document_type',
            field=models.CharField(choices=[('PO', 'Purchase Order'), ('DN', 'Delivery Note'), ('GRN', 'Goods Received Note'), ('INV', 'Invoice'), ('RCT', 'Receipt')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=60)),
                ('receipt_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.FileField(blank=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='procurement.procurementrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.supplier')),
            ],
        ),
    ]
