# Generated by Django 5.2 on 2026-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_deliverynote_items_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnumbersetting',
            name='document_type',
            field=models.CharField(choices=[('QTN', 'Quotation'), ('PO', 'Purchase Order'), ('DN', 'Delivery Note'), ('GRN', 'Goods Received Note'), ('INV', 'Invoice'), ('PAY', 'Payment Reference'), ('RCT', 'Receipt')], max_length=10, unique=True),
        ),
    ]
