# Generated by Django 5.1.4 on 2025-02-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="source",
            field=models.CharField(
                default="Unknown",
                help_text="Brand, restaurant, manufacturer, or shop name",
                max_length=200,
            ),
        ),
    ]
