# Generated by Django 5.1.4 on 2025-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_item_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image for the item",
                null=True,
                upload_to="item_images/",
            ),
        ),
    ]
