# Generated by Django 5.1.4 on 2025-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="referred_by",
            field=models.CharField(
                blank=True,
                help_text="Optional phone number of the person who recommended the items",
                max_length=15,
                null=True,
            ),
        ),
    ]
