# Generated by Django 5.1.4 on 2025-03-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_cart_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="billing_address",
            field=models.CharField(
                blank=True, help_text="Set your address", max_length=255, null=True
            ),
        ),
    ]
