# Generated by Django 5.1.4 on 2025-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_cart_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Physical location or storage place of the item",
                max_length=200,
                null=True,
            ),
        ),
    ]
