# Generated by Django 5.1.4 on 2025-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_item_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(default="Explore our wide range of products."),
        ),
        migrations.AddField(
            model_name="category",
            name="icon_class",
            field=models.CharField(default="fa-tag", max_length=50),
        ),
    ]
