# Generated by Django 5.1.4 on 2025-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_rename_category_itemcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("score", models.IntegerField(default=0)),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quiz Score",
                "verbose_name_plural": "Quiz Scores",
                "ordering": ["-score", "-date_submitted"],
            },
        ),
    ]
