# Generated by Django 5.1.4 on 2025-04-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_nsologame_nsoloboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nsologame",
            name="player1",
        ),
        migrations.RemoveField(
            model_name="nsologame",
            name="player2",
        ),
        migrations.RemoveField(
            model_name="nsologame",
            name="winner",
        ),
        migrations.DeleteModel(
            name="NsoloBoard",
        ),
        migrations.DeleteModel(
            name="NsoloGame",
        ),
    ]
