# Generated by Django 5.2.1 on 2025-07-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_business_referral_fee_paid_business_referred_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referred_business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="directory.business",
            ),
        ),
    ]
