# Generated by Django 5.1.4 on 2025-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_businessimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="business",
            name="longitude",
        ),
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businessimage",
            name="caption",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
