# Generated by Django 5.1.4 on 2025-02-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="advertisements/")),
                ("link", models.URLField(blank=True, null=True)),
                ("small_text", models.CharField(default="Paid Advert", max_length=100)),
                (
                    "slot",
                    models.IntegerField(
                        choices=[
                            (1, "Slot 1"),
                            (2, "Slot 2"),
                            (3, "Slot 3"),
                            (4, "Slot 4"),
                            (5, "Slot 5"),
                            (6, "Slot 6"),
                            (7, "Slot 7"),
                            (8, "Slot 8"),
                            (9, "Slot 9"),
                            (10, "Slot 10"),
                        ],
                        unique=True,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slot"],
            },
        ),
    ]
