# Generated by Django 5.2.1 on 2025-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_alter_referral_referred_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
        ),
    ]
