# Generated by Django 5.2.4 on 2025-08-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_alter_referral_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_marketing_emails",
            field=models.BooleanField(
                default=True, verbose_name="Receive marketing emails"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_message_emails",
            field=models.BooleanField(
                default=True, verbose_name="Receive message notifications via email"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="receive_notification_emails",
            field=models.BooleanField(
                default=True, verbose_name="Receive general notifications via email"
            ),
        ),
    ]
