# Generated by Django 5.1.4 on 2025-01-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_searchquery_alter_chatmessage_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
