# Generated by Django 5.2.4 on 2025-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_userprofile_receive_marketing_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="referral_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Total Referral Earnings",
            ),
        ),
    ]
