# Generated by Django 5.1.4 on 2025-02-26 14:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_alter_newsfeed_content_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsfeed",
            name="category",
            field=models.CharField(
                choices=[
                    ("story", "Story"),
                    ("weather", "Weather"),
                    ("food", "Food"),
                    ("news", "News"),
                    ("event", "Event"),
                    ("other", "Other"),
                ],
                default="news",
                max_length=50,
            ),
        ),
    ]
