# Generated by Django 5.2.4 on 2025-08-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_userprofile_referral_earnings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="referral_earnings",
        ),
    ]
