# Generated by Django 5.1.4 on 2025-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_alter_business_description_alter_newsfeed_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsfeed",
            name="category",
            field=models.CharField(
                choices=[
                    ("story", "Story"),
                    ("weather", "Weather"),
                    ("food", "Food"),
                    ("news", "News"),
                    ("event", "Event"),
                    ("sports", "Sports"),
                    ("over18", "Over 18"),
                    ("other", "Other"),
                ],
                default="news",
                max_length=50,
            ),
        ),
    ]
