# Generated by Django 5.2.4 on 2025-08-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0007_remove_userprofile_referral_earnings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=10),
        ),
    ]
