# Generated by Django 5.2.4 on 2025-09-04 08:29

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0010_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone_verified",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="US", unique=True
            ),
        ),
    ]
