# Generated by Django 5.1.4 on 2025-05-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0012_businesspostgalleryimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessimage",
            options={"ordering": ["-is_primary", "-created_at"]},
        ),
        migrations.AddField(
            model_name="businessimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Set as primary image for the business"
            ),
        ),
        migrations.AlterField(
            model_name="businessimage",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="business_images/"
            ),
            preserve_default=False,
        ),
    ]
