# Generated by Django 5.2.4 on 2025-09-04 11:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0012_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="0000000000", max_length=128, region="US", unique=True
            ),
            preserve_default=False,
        ),
    ]
