# Generated by Django 5.2.4 on 2025-09-18 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0014_alter_userprofile_phone_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="verification_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verification Date"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_businesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Verified by",
            ),
        ),
    ]
