# Generated by Django 5.2.1 on 2025-06-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0014_alter_businessimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="show_store_link",
            field=models.BooleanField(
                default=True,
                help_text="Toggle to show/hide the store link in navigation",
                verbose_name="Show Store Link",
            ),
        ),
    ]
