# Generated by Django 5.2.4 on 2025-09-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0015_business_verification_date_business_verified_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"permissions": [("can_verify", "Can verify business")]},
        ),
    ]
