# Generated by Django 5.2.1 on 2025-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0015_business_show_store_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="verified_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Date until which this business remains verified",
                null=True,
                verbose_name="Verification End Date",
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="is_admin_added",
            field=models.BooleanField(default=False, verbose_name="Verified Status"),
        ),
    ]
